#file: deploy.yml
- hosts: all
  become: yes
  vars_files:
    - "group_vars/{{ env }}.yml"

  tasks:
    - name: Create www path
      file:
        path: /var/www/{{ env }}-mtwork.dashboard
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Create the configurations for app
      template:
        src: templates/dashboard_site.conf.j2
        dest: /etc/nginx/sites-available/{{ env }}-mtwork.dashboard.conf

    - name: Create links for sites-enabled
      file:
        state: link
        src: /etc/nginx/sites-available/{{ env }}-mtwork.dashboard.conf
        dest: /etc/nginx/sites-enabled/{{ env }}-mtwork.dashboard.conf

    - name: restart nginx
      systemd:
        name: nginx
        daemon_reload: yes
        state: restarted
