export const data = (raw = {}) => {
  const {
    ref1Prefix,
    // ref1PrefixMsg,
    ref1Firstname,
    // ref1FirstnameMsg,
    ref1Lastname,
    // ref1LastnameMsg,
    ref1Relationship,
    ref1Mobile,
    // ref1MobileMsg,
    ref1WorkTelephone,
    // ref1WorkTelephoneMsg,
    ref1HomeTelephone,
    // ref1HomeTelephoneMsg,
    ref2Prefix,
    // ref2PrefixMsg,
    ref2Firstname,
    // ref2FirstnameMsg,
    ref2Lastname,
    // ref2LastnameMsg,
    ref2Relationship,
    ref2Mobile,
    // ref2MobileMsg,
    ref2WorkTelephone,
    // ref2WorkTelephoneMsg,
    ref2HomeTelephone,
    // ref2HomeTelephoneMsg,
    conjugalPrefix,
    // conjugalPrefixMsg,
    conjugalFirstname,
    // conjugalFirstnameMsg,
    conjugalLastname,
    // conjugalLastnameMsg,
    conjugalOccupation,
    // conjugalOccupationMsg,
    conjugalIncome,
    // conjugalIncomeMsg,
    children,
    //
    shippingHouseNo,
    shippingMoo,
    shippingVillage,
    shippingFloor,
    shippingSoi,
    shippingRoad,
    shippingPostalCode,
    shippingProvinceCode,
    shippingAmphurCode,
    shippingTambolCode,
    shippingProvinceCodeName,
    shippingAmphurCodeName,
    shippingTambolCodeName,
    shippingAddress,
    //
    isConsent2,
    //
    files,
    //
    fileName0,
    fileName1,
    fileName2,
    fileName3,
    fileName4,
    fileName5,
    fileName6,
  } = raw;

  // ref1PrefixMsg,
  // ref1FirstnameMsg,
  // ref1LastnameMsg,
  // ref1MobileMsg,
  // ref1WorkTelephoneMsg,
  // ref1HomeTelephoneMsg,
  // ref2PrefixMsg,
  // ref2FirstnameMsg,
  // ref2MobileMsg,
  // ref2LastnameMsg,
  // ref2WorkTelephoneMsg,
  // ref2HomeTelephoneMsg,
  // conjugalPrefixMsg,
  // conjugalFirstnameMsg,
  // conjugalLastnameMsg,
  // conjugalOccupationMsg,
  // conjugalIncomeMsg,
  return {
    ref1Prefix: ref1Prefix || '',
    ref1Firstname: ref1Firstname || '',
    ref1Lastname: ref1Lastname || '',
    ref1Relationship: ref1Relationship || '',
    ref1Mobile: ref1Mobile || '',
    ref1WorkTelephone: ref1WorkTelephone || '',
    ref1HomeTelephone: ref1HomeTelephone || '',
    //
    ref2Prefix: ref2Prefix || '',
    ref2Firstname: ref2Firstname || '',
    ref2Lastname: ref2Lastname || '',
    ref2Relationship: ref2Relationship || '',
    ref2Mobile: ref2Mobile || '',
    ref2WorkTelephone: ref2WorkTelephone || '',
    ref2HomeTelephone: ref2HomeTelephone || '',
    //
    conjugalPrefix: conjugalPrefix || '',
    conjugalFirstname: conjugalFirstname || '',
    conjugalLastname: conjugalLastname || '',
    conjugalOccupation: conjugalOccupation || '',
    conjugalIncome: conjugalIncome || 0,
    children: children || 0,
    //
    shippingHouseNo: shippingHouseNo || '',
    shippingMoo: shippingMoo || '',
    shippingVillage: shippingVillage || '',
    shippingFloor: shippingFloor || '',
    shippingSoi: shippingSoi || '',
    shippingRoad: shippingRoad || '',
    shippingPostalCode: shippingPostalCode || '',
    shippingProvinceCode: shippingProvinceCode || '',
    shippingAmphurCode: shippingAmphurCode || '',
    shippingTambolCode: shippingTambolCode || '',
    shippingProvinceCodeName: shippingProvinceCodeName || '',
    shippingAmphurCodeName: shippingAmphurCodeName || '',
    shippingTambolCodeName: shippingTambolCodeName || '',
    shippingAddress: shippingAddress || 'current',
    //
    isConsent2: isConsent2 || false,
    //
    files: files || [],
    //
    fileName0: fileName0 || '',
    fileName1: fileName1 || '',
    fileName2: fileName2 || '',
    fileName3: fileName3 || '',
    fileName4: fileName4 || '',
    fileName5: fileName5 || '',
    fileName6: fileName6 || '',
  };
};

export default {
  data,
};
