import moment from 'moment';
// import { dateFormat } from '../libs/config';

export const parseLeadIn = ({
  ID,
  CreatedAt,
  UpdatedAt,
  DeletedAt,
  UserID,
  Email,
  IDCard,
  MobileNo,
  BirthDate,
  TicketID,
  Status,
  ReferenceID,
  Data,
}) => {
  let entry = JSON.parse(Data) || {};
  const { prefixTH, firstNameTH, lastNameTH } = entry;
  const nameTH = `${prefixTH || ''} ${firstNameTH || ''} ${lastNameTH || ''}`.trim();

  entry = Object.assign({
    ID,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    UserID,
    Email,
    IDCard,
    MobileNo,
    BirthDate,
    TicketID,
    Status,
    ReferenceID,
  },
    entry,
    { nameTH },
  );

  return entry;
};

export const split = data => {
  const {
    dateReq,
    prefixTH,
    firstNameTH,
    lastNameTH,
    prefixEN,
    firstNameEN,
    lastNameEN,
    idCard,
    dateExp,
    status,
    department,
    position,
    workTel2,
    homeTel2,
    detailRent,
    workTel,
    workTelValid,
    telExtension,
    number,
    moo,
    village,
    soi,
    road,
    province,
    amphurCode,
    tambolCode,
    provinceName,
    amphurCodeName,
    tambolCodeName,
    zipCode,
    number2,
    moo2,
    village2,
    soi2,
    road2,
    zipCode2,
    isSameAddress,
    jobCompanyName,
    birthDate,
    email,
    employmentDate,
    jobSalary,
    //
    officeNumber,
    officeMoo,
    officeVillage,
    officeSoi,
    officeRoad,
    officeProvince,
    officeAmphurCode,
    officeTambolCode,
    officeProvinceName,
    officeAmphurCodeName,
    officeTambolCodeName,
    officeZipCode,
    //
    loanAmount,
    installmentNumber,
    beneficiary,
    loanBeneficiaryName,
    accumulateDebt,
    creditCardTotal,
    paymentHistoryExists,
    pLoanApplicationHositoryExists,
    overdueDebtExists,
    bankAccountNo,
    bankAccountName,
    bankCode,
    bankName,
    bankBranchName,
    //
    ref1Prefix,
    ref1PrefixMsg,
    ref1Firstname,
    ref1FirstnameMsg,
    ref1Lastname,
    ref1LastnameMsg,
    ref1Relationship,
    ref1Mobile,
    ref1MobileMsg,
    ref1WorkTelephone,
    ref1WorkTelephoneMsg,
    ref1HomeTelephone,
    ref1HomeTelephoneMsg,
    ref2Prefix,
    ref2PrefixMsg,
    ref2Firstname,
    ref2FirstnameMsg,
    ref2Lastname,
    ref2LastnameMsg,
    ref2Relationship,
    ref2Mobile,
    ref2MobileMsg,
    ref2WorkTelephone,
    ref2WorkTelephoneMsg,
    ref2HomeTelephone,
    ref2HomeTelephoneMsg,
    conjugalPrefix,
    conjugalPrefixMsg,
    conjugalFirstname,
    conjugalFirstnameMsg,
    conjugalLastname,
    conjugalLastnameMsg,
    conjugalOccupation,
    conjugalOccupationMsg,
    conjugalIncome,
    conjugalIncomeMsg,
    children,
    //
    shippingHouseNo,
    shippingMoo,
    shippingVillage,
    shippingFloor,
    shippingSoi,
    shippingRoad,
    shippingPostalCode,
    shippingProvinceCode,
    shippingAmphurCode,
    shippingTambolCode,
    shippingProvinceCodeName,
    shippingAmphurCodeName,
    shippingTambolCodeName,
    shippingAddress,
    //
    isConsent2,
  } = data;

  console.log('lead: ', dateReq, birthDate, dateExp, employmentDate);

  const personalInfo = {
    dateReq: dateReq ? moment(dateReq).toDate() : null,
    prefixTH,
    firstNameTH,
    lastNameTH,
    prefixEN,
    firstNameEN,
    lastNameEN,
    idCard,
    dateExp: dateExp ? moment(dateExp).toDate() : null,
    status,
    department,
    position,
    workTel2,
    homeTel2,
    detailRent,
    workTel,
    workTelValid,
    telExtension,
    number,
    moo,
    village,
    soi,
    road,
    province,
    amphurCode,
    tambolCode,
    provinceName,
    amphurCodeName,
    tambolCodeName,
    zipCode,
    number2,
    moo2,
    village2,
    soi2,
    road2,
    zipCode2,
    isSameAddress,
    jobCompanyName,
    birthDate: birthDate ? moment(birthDate).toDate() : null,
    email,
    employmentDate: employmentDate ? moment(employmentDate).toDate() : null,
    jobSalary,
    //
    officeNumber,
    officeMoo,
    officeVillage,
    officeSoi,
    officeRoad,
    officeProvince,
    officeAmphurCode,
    officeTambolCode,
    officeProvinceName,
    officeAmphurCodeName,
    officeTambolCodeName,
    officeZipCode,
    //
  };

  const loanInfo = {
    loanAmount,
    installmentNumber,
    beneficiary,
    loanBeneficiaryName,
    accumulateDebt,
    creditCardTotal,
    paymentHistoryExists,
    pLoanApplicationHositoryExists,
    overdueDebtExists,
    bankAccountNo,
    bankAccountName,
    bankCode,
    bankName,
    bankBranchName,
  };

  const additionalInfo = {
    ref1Prefix,
    ref1PrefixMsg,
    ref1Firstname,
    ref1FirstnameMsg,
    ref1Lastname,
    ref1LastnameMsg,
    ref1Relationship,
    ref1Mobile,
    ref1MobileMsg,
    ref1WorkTelephone,
    ref1WorkTelephoneMsg,
    ref1HomeTelephone,
    ref1HomeTelephoneMsg,
    ref2Prefix,
    ref2PrefixMsg,
    ref2Firstname,
    ref2FirstnameMsg,
    ref2Lastname,
    ref2LastnameMsg,
    ref2Relationship,
    ref2Mobile,
    ref2MobileMsg,
    ref2WorkTelephone,
    ref2WorkTelephoneMsg,
    ref2HomeTelephone,
    ref2HomeTelephoneMsg,
    conjugalPrefix,
    conjugalPrefixMsg,
    conjugalFirstname,
    conjugalFirstnameMsg,
    conjugalLastname,
    conjugalLastnameMsg,
    conjugalOccupation,
    conjugalOccupationMsg,
    conjugalIncome,
    conjugalIncomeMsg,
    children,
    //
    shippingHouseNo,
    shippingMoo,
    shippingVillage,
    shippingFloor,
    shippingSoi,
    shippingRoad,
    shippingPostalCode,
    shippingProvinceCode,
    shippingAmphurCode,
    shippingTambolCode,
    shippingProvinceCodeName,
    shippingAmphurCodeName,
    shippingTambolCodeName,
    shippingAddress,
    //
    isConsent2,
  };

  return {
    personalInfo,
    loanInfo,
    additionalInfo,
  };
};
